# Pingus - A free Lemmings clone
# Copyright (C) 2015 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Build file for https://travis-ci.org/
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Based on:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# https://github.com/SuperTux/supertux/blob/master/.travis.yml

language: cpp

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

env:
  global:
    - CMAKE_VERSION=3.2.1 SDL2_VERSION=2.0.3 SDL2IMAGE_VERSION=2.0.0 SDL2MIXER_VERSION=2.0.0
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "CPJBu4r8RDmeP7G78ODyk+A/J3vxEFr4xpQE0zIDtdCHcQmv2NqjM88YVH5pRWK4vtpAFuDEzyw4ZGKwfmwK5zhg2nUubsf47WpQmQa0z9HLasjXATzWwXGggx7mzlKODpkkccBzXHDAqvLKTkKBeXdxwMKFCtSgEM+3MwEwW6g="
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libogg-dev libvorbis-dev libphysfs-dev libglew-dev libopenal-dev libjsoncpp-dev

  # Current gcc that supports C++ 11 features
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

  # boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-filesystem1.55-dev libboost-signals1.55-dev libboost-system1.55-dev

  # manual boost compile
  #- wget --no-check-certificate http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.gz -O - | tar xz
  #- (cd boost_1_58_0/ && ./bootstrap.sh --with-libraries=filesystem,signals,system && ./b2 && ./b2 install)

  # CMake
  - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-$CMAKE_VERSION.tar.gz -O - | tar xz
  - (cd cmake-$CMAKE_VERSION && cmake . && make -j3 && sudo make install)

  # SDL dependencies
  - wget --no-check-certificate http://libsdl.org/release/SDL2-$SDL2_VERSION.tar.gz -O - | tar xz
  - (cd SDL2-$SDL2_VERSION && ./configure --prefix=/usr && make -j3 && sudo make install)
  - wget --no-check-certificate http://www.libsdl.org/projects/SDL_image/release/SDL2_image-$SDL2IMAGE_VERSION.tar.gz -O - | tar xz
  - (cd SDL2_image-$SDL2IMAGE_VERSION && ./configure --prefix=/usr && make -j3 && sudo make install)
  - wget --no-check-certificate http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-$SDL2MIXER_VERSION.tar.gz -O - | tar xz
  - (cd SDL2_mixer-$SDL2MIXER_VERSION && ./configure --prefix=/usr && make -j3 && sudo make install)

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON -DBUILD_EXTRA=ON
  - make VERBOSE=1 -j3
  - (cd .. && build-${BUILD_TYPE}/test_pingus)

# The branch coverity_scan is used to trigger the start of a coverity
# scan, merge the latest development version into and push it to start
# the scan.
addons:
  coverity_scan:
    project:
      name: "Pingus/pingus"
      description: "Build submitted via Travis CI"
    notification_email: grumbel@gmail.com
    build_command_prepend: "cmake . && make clean"
    build_command: "make -j 3"
    branch_pattern: coverity_scan

# EOF #
